/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { MatchRecord } from './types';

export const FALLBACK_RECORDS: MatchRecord[] = [
  {
    id: "f1",
    temporada: "2025-2026",
    fecha: "2025-09-21",
    competicion: "LIGA VASCA JUVENIL / GAZTEEN EUSKAL LIGA",
    campo: "GOBELA",
    equipoLocal: "ROMO F.C.",
    equipoVisitante: "BEASAIN, S.D.",
    jornada: "JORNADA 2",
    partido: "ROMO F.C. - BEASAIN, S.D.",
    golesLocal: 3,
    golesVisitante: 0,
    resultado: "3 - 0",
    equipo: "ROMO F.C.",
    dorsal: 1,
    jugador: "ZARATE LANDEA, AIMAR",
    titular: true,
    suplente: false,
    minutosJugados: 90,
    golesAnotados: 0,
    tarjetaAmarilla: 0,
    dobleAmarilla: 0,
    tarjetaRoja: 0
  },
  {
    id: "f2",
    temporada: "2025-2026",
    fecha: "2025-09-21",
    competicion: "LIGA VASCA JUVENIL / GAZTEEN EUSKAL LIGA",
    campo: "GOBELA",
    equipoLocal: "ROMO F.C.",
    equipoVisitante: "BEASAIN, S.D.",
    jornada: "JORNADA 2",
    partido: "ROMO F.C. - BEASAIN, S.D.",
    golesLocal: 3,
    golesVisitante: 0,
    resultado: "3 - 0",
    equipo: "ROMO F.C.",
    dorsal: 3,
    jugador: "RIVAS LOPATEGI, UNAI",
    titular: true,
    suplente: false,
    minutosJugados: 90,
    golesAnotados: 0,
    tarjetaAmarilla: 0,
    dobleAmarilla: 0,
    tarjetaRoja: 0
  },
  {
    id: "f3",
    temporada: "2025-2026",
    fecha: "2025-09-21",
    competicion: "LIGA VASCA JUVENIL / GAZTEEN EUSKAL LIGA",
    campo: "GOBELA",
    equipoLocal: "ROMO F.C.",
    equipoVisitante: "BEASAIN, S.D.",
    jornada: "JORNADA 2",
    partido: "ROMO F.C. - BEASAIN, S.D.",
    golesLocal: 3,
    golesVisitante: 0,
    resultado: "3 - 0",
    equipo: "ROMO F.C.",
    dorsal: 4,
    jugador: "VILLAR MONTALVO, EDER",
    titular: true,
    suplente: false,
    minutosJugados: 90,
    golesAnotados: 0,
    tarjetaAmarilla: 0,
    dobleAmarilla: 0,
    tarjetaRoja: 0
  },
  {
    id: "f4",
    temporada: "2025-2026",
    fecha: "2025-09-21",
    competicion: "LIGA VASCA JUVENIL / GAZTEEN EUSKAL LIGA",
    campo: "GOBELA",
    equipoLocal: "ROMO F.C.",
    equipoVisitante: "BEASAIN, S.D.",
    jornada: "JORNADA 2",
    partido: "ROMO F.C. - BEASAIN, S.D.",
    golesLocal: 3,
    golesVisitante: 0,
    resultado: "3 - 0",
    equipo: "ROMO F.C.",
    dorsal: 5,
    jugador: "ESKUBI HERVAS, IKER",
    titular: true,
    suplente: false,
    minutosJugados: 90,
    golesAnotados: 0,
    tarjetaAmarilla: 0,
    dobleAmarilla: 0,
    tarjetaRoja: 0
  },
  {
    id: "f5",
    temporada: "2025-2026",
    fecha: "2025-09-21",
    competicion: "LIGA VASCA JUVENIL / GAZTEEN EUSKAL LIGA",
    campo: "GOBELA",
    equipoLocal: "ROMO F.C.",
    equipoVisitante: "BEASAIN, S.D.",
    jornada: "JORNADA 2",
    partido: "ROMO F.C. - BEASAIN, S.D.",
    golesLocal: 3,
    golesVisitante: 0,
    resultado: "3 - 0",
    equipo: "ROMO F.C.",
    dorsal: 10,
    jugador: "CHAPARRO RUIZ, IKER",
    titular: true,
    suplente: false,
    minutosJugados: 85,
    golesAnotados: 2,
    tarjetaAmarilla: 0,
    dobleAmarilla: 0,
    tarjetaRoja: 0
  },
  {
    id: "f6",
    temporada: "2025-2026",
    fecha: "2025-09-21",
    competicion: "LIGA VASCA JUVENIL / GAZTEEN EUSKAL LIGA",
    campo: "GOBELA",
    equipoLocal: "ROMO F.C.",
    equipoVisitante: "BEASAIN, S.D.",
    jornada: "JORNADA 2",
    partido: "ROMO F.C. - BEASAIN, S.D.",
    golesLocal: 3,
    golesVisitante: 0,
    resultado: "3 - 0",
    equipo: "ROMO F.C.",
    dorsal: 9,
    jugador: "GODWIN OSAS, STANLEY",
    titular: true,
    suplente: false,
    minutosJugados: 45,
    golesAnotados: 1,
    tarjetaAmarilla: 0,
    dobleAmarilla: 0,
    tarjetaRoja: 0
  },
  {
    id: "f7",
    temporada: "2025-2026",
    fecha: "2025-09-21",
    competicion: "LIGA VASCA JUVENIL / GAZTEEN EUSKAL LIGA",
    campo: "GOBELA",
    equipoLocal: "ROMO F.C.",
    equipoVisitante: "BEASAIN, S.D.",
    jornada: "JORNADA 2",
    partido: "ROMO F.C. - BEASAIN, S.D.",
    golesLocal: 3,
    golesVisitante: 0,
    resultado: "3 - 0",
    equipo: "BEASAIN, S.D.",
    dorsal: 1,
    jugador: "OTAMENDI GOMEZ, LANDER",
    titular: true,
    suplente: false,
    minutosJugados: 90,
    golesAnotados: 0,
    tarjetaAmarilla: 0,
    dobleAmarilla: 0,
    tarjetaRoja: 0
  },
  {
    id: "f8",
    temporada: "2025-2026",
    fecha: "2025-09-21",
    competicion: "LIGA VASCA JUVENIL / GAZTEEN EUSKAL LIGA",
    campo: "GOBELA",
    equipoLocal: "ROMO F.C.",
    equipoVisitante: "BEASAIN, S.D.",
    jornada: "JORNADA 2",
    partido: "ROMO F.C. - BEASAIN, S.D.",
    golesLocal: 3,
    golesVisitante: 0,
    resultado: "3 - 0",
    equipo: "BEASAIN, S.D.",
    dorsal: 5,
    jugador: "ARTEAGA AMUNDARAIN, MIKEL",
    titular: true,
    suplente: false,
    minutosJugados: 90,
    golesAnotados: 0,
    tarjetaAmarilla: 1,
    dobleAmarilla: 0,
    tarjetaRoja: 0
  },
  {
    id: "f9",
    temporada: "2025-2026",
    fecha: "2025-09-28",
    competicion: "LIGA VASCA JUVENIL / GAZTEEN EUSKAL LIGA",
    campo: "GOBELA",
    equipoLocal: "ROMO F.C.",
    equipoVisitante: "ARIZNABARRA",
    jornada: "JORNADA 3",
    partido: "ROMO F.C. - ARIZNABARRA",
    golesLocal: 5,
    golesVisitante: 2,
    resultado: "5 - 2",
    equipo: "ROMO F.C.",
    dorsal: 10,
    jugador: "CHAPARRO RUIZ, IKER",
    titular: true,
    suplente: false,
    minutosJugados: 90,
    golesAnotados: 3,
    tarjetaAmarilla: 1,
    dobleAmarilla: 0,
    tarjetaRoja: 0
  },
  {
    id: "f10",
    temporada: "2025-2026",
    fecha: "2025-09-28",
    competicion: "LIGA VASCA JUVENIL / GAZTEEN EUSKAL LIGA",
    campo: "GOBELA",
    equipoLocal: "ROMO F.C.",
    equipoVisitante: "ARIZNABARRA",
    jornada: "JORNADA 3",
    partido: "ROMO F.C. - ARIZNABARRA",
    golesLocal: 5,
    golesVisitante: 2,
    resultado: "5 - 2",
    equipo: "ROMO F.C.",
    dorsal: 9,
    jugador: "GODWIN OSAS, STANLEY",
    titular: true,
    suplente: false,
    minutosJugados: 75,
    golesAnotados: 1,
    tarjetaAmarilla: 0,
    dobleAmarilla: 0,
    tarjetaRoja: 0
  },
  {
    id: "f11",
    temporada: "2025-2026",
    fecha: "2025-09-28",
    competicion: "LIGA VASCA JUVENIL / GAZTEEN EUSKAL LIGA",
    campo: "GOBELA",
    equipoLocal: "ROMO F.C.",
    equipoVisitante: "ARIZNABARRA",
    jornada: "JORNADA 3",
    partido: "ROMO F.C. - ARIZNABARRA",
    golesLocal: 5,
    golesVisitante: 2,
    resultado: "5 - 2",
    equipo: "ROMO F.C.",
    dorsal: 7,
    jugador: "ARTETXE BAYON, BEÑAT",
    titular: true,
    suplente: false,
    minutosJugados: 90,
    golesAnotados: 1,
    tarjetaAmarilla: 0,
    dobleAmarilla: 0,
    tarjetaRoja: 0
  },
  {
    id: "f12",
    temporada: "2025-2026",
    fecha: "2025-09-28",
    competicion: "LIGA VASCA JUVENIL / GAZTEEN EUSKAL LIGA",
    campo: "GOBELA",
    equipoLocal: "ROMO F.C.",
    equipoVisitante: "ARIZNABARRA",
    jornada: "JORNADA 3",
    partido: "ROMO F.C. - ARIZNABARRA",
    golesLocal: 5,
    golesVisitante: 2,
    resultado: "5 - 2",
    equipo: "ARIZNABARRA",
    dorsal: 9,
    jugador: "HERRAN GONZALEZ, LANDER",
    titular: true,
    suplente: false,
    minutosJugados: 90,
    golesAnotados: 2,
    tarjetaAmarilla: 0,
    dobleAmarilla: 0,
    tarjetaRoja: 0
  },
  {
    id: "f13",
    temporada: "2025-2026",
    fecha: "2025-09-28",
    competicion: "LIGA VASCA JUVENIL / GAZTEEN EUSKAL LIGA",
    campo: "GOBELA",
    equipoLocal: "ROMO F.C.",
    equipoVisitante: "ARIZNABARRA",
    jornada: "JORNADA 3",
    partido: "ROMO F.C. - ARIZNABARRA",
    golesLocal: 5,
    golesVisitante: 2,
    resultado: "5 - 2",
    equipo: "ARIZNABARRA",
    dorsal: 4,
    jugador: "DE DIEGO LOPEZ DE ARAYA, ANDONI",
    titular: true,
    suplente: false,
    minutosJugados: 90,
    golesAnotados: 0,
    tarjetaAmarilla: 1,
    dobleAmarilla: 0,
    tarjetaRoja: 0
  },
  {
    id: "f14",
    temporada: "2025-2026",
    fecha: "2025-09-28",
    competicion: "LIGA VASCA JUVENIL / GAZTEEN EUSKAL LIGA",
    campo: "GOBELA",
    equipoLocal: "ROMO F.C.",
    equipoVisitante: "ARIZNABARRA",
    jornada: "JORNADA 3",
    partido: "ROMO F.C. - ARIZNABARRA",
    golesLocal: 5,
    golesVisitante: 2,
    resultado: "5 - 2",
    equipo: "ROMO F.C.",
    dorsal: 14,
    jugador: "LOPEZ CHAVARRI, KEVIN",
    titular: false,
    suplente: true,
    minutosJugados: 15,
    golesAnotados: 0,
    tarjetaAmarilla: 0,
    dobleAmarilla: 0,
    tarjetaRoja: 0
  },
  {
    id: "f15",
    temporada: "2025-2026",
    fecha: "2025-09-28",
    competicion: "LIGA VASCA JUVENIL / GAZTEEN EUSKAL LIGA",
    campo: "GOBELA",
    equipoLocal: "ROMO F.C.",
    equipoVisitante: "ARIZNABARRA",
    jornada: "JORNADA 3",
    partido: "ROMO F.C. - ARIZNABARRA",
    golesLocal: 5,
    golesVisitante: 2,
    resultado: "5 - 2",
    equipo: "ROMO F.C.",
    dorsal: 15,
    jugador: "SANCHEZ ARANA, JONATHAN",
    titular: false,
    suplente: true,
    minutosJugados: 45,
    golesAnotados: 0,
    tarjetaAmarilla: 0,
    dobleAmarilla: 0,
    tarjetaRoja: 0
  }
];
